---
- hosts: mesos_master:mesos_slave

  tasks:
    - name: Update All nodes
      apt: update_cache=yes upgrade=dist

    - name: Updating Nodes /etc/hosts files
      lineinfile: 
        dest: /etc/hosts 
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}" 
        state: present
      with_items: "{{play_hosts}}"

    - name: Add Mesos Repo Key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=E56151BF
    - name: Add Mesos Repo 
      apt_repository: repo='deb http://repos.mesosphere.com/ubuntu trusty main' state=present
    - name: Install Mesos 
      apt: name=mesos state=present update_cache=yes

    - name: Creating template for mesos configuration
      command: echo
          {% for item in groups['mesos_master'] -%}
              {{ hostvars[item].ansible_default_ipv4.address }}:2181,
          {%- endfor %}
      register: ip_out
    - name: Clearing template
      shell: echo {{ip_out.stdout}} | rev | cut -c 2- | rev
      register: zk_out
    - name: Apply template to mesos configuration file
      shell: echo "zk://{{zk_out.stdout}}/mesos" > /etc/mesos/zk



