---
- hosts: mesos_slave

  tasks:
    - name: Add Docker keyserver on Slave nodes
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D 

    - name: Add Docker Repo
      shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list

    - name: Update packages
      apt: update_cache=yes

    - name: Purge existing installation
      apt: name=lxc-docker state=absent purge=yes

    - name: Pull repo
      command: apt-cache policy docker-engine

    - name: Upgrade
      apt: upgrade=yes

    - name: Get linux-image-extra package name
      shell: echo linux-image-extra-$(uname -r)
      register: lie

    - name: Install linux-image-extra
      apt: name="{{lie.stdout}}" update_cache=yes

    - name: Install Docker engine
      apt: name=docker-engine state=present

    - name: Start docker service
      service: name="{{item}}" state=reloaded
      with_items:
        - docker
        - mesos-slave






